name: CI

on:
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python -m pip install -r requirements.txt

      # Cache pre-commit hooks
      # See https://pre-commit.com/#github-actions-example
      - name: set Python checksum for cache
        run: echo "PY_CHECKSUM=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY_CHECKSUM }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run CI checking
        run: npm run ci
